/**
 * Created by peteryao on 2/11/20.
 */

const getUSStateOptions = () => {
    return [
        {value: 'AK', label: 'AK'},
        {value: 'AL', label: 'AL'},
        {value: 'AR', label: 'AR'},
        {value: 'AZ', label: 'AZ'},
        {value: 'CA', label: 'CA'},
        {value: 'CO', label: 'CO'},
        {value: 'CT', label: 'CT'},
        {value: 'DE', label: 'DE'},
        {value: 'FL', label: 'FL'},
        {value: 'GA', label: 'GA'},
        {value: 'HI', label: 'HI'},
        {value: 'IA', label: 'IA'},
        {value: 'ID', label: 'ID'},
        {value: 'IL', label: 'IL'},
        {value: 'IN', label: 'IN'},
        {value: 'KS', label: 'KS'},
        {value: 'KY', label: 'KY'},
        {value: 'LA', label: 'LA'},
        {value: 'MA', label: 'MA'},
        {value: 'MD', label: 'MD'},
        {value: 'ME', label: 'ME'},
        {value: 'MI', label: 'MI'},
        {value: 'MN', label: 'MN'},
        {value: 'MO', label: 'MO'},
        {value: 'MS', label: 'MS'},
        {value: 'MT', label: 'MT'},
        {value: 'NC', label: 'NC'},
        {value: 'ND', label: 'ND'},
        {value: 'NE', label: 'NE'},
        {value: 'NH', label: 'NH'},
        {value: 'NJ', label: 'NJ'},
        {value: 'NM', label: 'NM'},
        {value: 'NV', label: 'NV'},
        {value: 'NY', label: 'NY'},
        {value: 'OH', label: 'OH'},
        {value: 'OK', label: 'OK'},
        {value: 'OR', label: 'OR'},
        {value: 'PA', label: 'PA'},
        {value: 'RI', label: 'RI'},
        {value: 'SC', label: 'SC'},
        {value: 'SD', label: 'SD'},
        {value: 'TN', label: 'TN'},
        {value: 'TX', label: 'TX'},
        {value: 'UT', label: 'UT'},
        {value: 'VA', label: 'VA'},
        {value: 'VT', label: 'VT'},
        {value: 'WA', label: 'WA'},
        {value: 'WI', label: 'WI'},
        {value: 'WV', label: 'WV'},
        {value: 'WY', label: 'WY'}
    ];
};

const getUSStateOptionsFull = () => {
    return [
        {value: 'AK', label: 'Alaska'},
        {value: 'AL', label: 'Alabama'},
        {value: 'AR', label: 'Arkansas'},
        {value: 'AZ', label: 'Arizona'},
        {value: 'CA', label: 'California'},
        {value: 'CO', label: 'Colorado'},
        {value: 'CT', label: 'Connecticut'},
        {value: 'DE', label: 'Delaware'},
        {value: 'DC', label: 'District of Columbia'},
        {value: 'FL', label: 'Florida'},
        {value: 'GA', label: 'Georgia'},
        {value: 'HI', label: 'Hawaii'},
        {value: 'IA', label: 'Iowa'},
        {value: 'ID', label: 'Idaho'},
        {value: 'IL', label: 'Illinois'},
        {value: 'IN', label: 'Indiana'},
        {value: 'KS', label: 'Kansas'},
        {value: 'KY', label: 'Kentucky'},
        {value: 'LA', label: 'Louisiana'},
        {value: 'MA', label: 'Massachusetts'},
        {value: 'MD', label: 'Maryland'},
        {value: 'ME', label: 'Maine'},
        {value: 'MI', label: 'Michigan'},
        {value: 'MN', label: 'Minnesota'},
        {value: 'MO', label: 'Missouri'},
        {value: 'MS', label: 'Mississippi'},
        {value: 'MT', label: 'Montana'},
        {value: 'NC', label: 'North Carolina'},
        {value: 'ND', label: 'North Dakota'},
        {value: 'NE', label: 'Nebraska'},
        {value: 'NH', label: 'New Hampshire'},
        {value: 'NJ', label: 'New Jersey'},
        {value: 'NM', label: 'New Mexico'},
        {value: 'NV', label: 'Nevada'},
        {value: 'NY', label: 'New York'},
        {value: 'OH', label: 'Ohio'},
        {value: 'OK', label: 'Oklahoma'},
        {value: 'OR', label: 'Oregon'},
        {value: 'PA', label: 'Pennsylvania'},
        {value: 'RI', label: 'Rhode Island'},
        {value: 'SC', label: 'South Carolina'},
        {value: 'SD', label: 'South Dakota'},
        {value: 'TN', label: 'Tennessee'},
        {value: 'TX', label: 'Texas'},
        {value: 'UT', label: 'Utah'},
        {value: 'VA', label: 'Virginia'},
        {value: 'VT', label: 'Vermont'},
        {value: 'WA', label: 'Washington'},
        {value: 'WI', label: 'Wisconsin'},
        {value: 'WV', label: 'West Virginia'},
        {value: 'WY', label: 'Wyoming'}
    ];
};

export {getUSStateOptions}

export {getUSStateOptionsFull}