Id,Name,Type,RecordTypeId,BillingCountry,ShippingCountry,Recurring_Billing__c,Send_Checks_Address__c,Directions_to_Write_Paper_Check__c
TestAccountA,Account A,Landowner,012j00000010Ha3AAE,United States,United States,true,BlueWave 137 Newbury Street Boston MA 02114,No Payment Due
TestAccountB,Account B,Landowner,012j00000010Ha3AAE,United States,United States,true,BlueWave 137 Newbury Street Boston MA 02114,No Payment Due
TestAccountC,Account C,Landowner,012j00000010Ha3AAE,United States,United States,true,,
TestAccountD,Account D,Landowner,012j00000010Ha3AAE,United States,United States,true,,