Id,AccountId,RecordTypeId,Name,StageName,CloseDate,Shared_Solar_System__c
TestAccountAOppOne,TestAccountA,012j0000000tL1yAAE,OppOne,Complete,2018-08-20 00:00:00,TestSolarSystem-BarrettP1
TestAccountAOppTwo,TestAccountA,012j0000000tL1yAAE,OppTwo,Complete,2018-08-20 00:00:00,TestSolarSystem-BarrettP2
TestAccountBOpp,TestAccountB,012j0000000tL1yAAE,OppThree,Complete,2018-08-20 00:00:00,TestSolarSystem-BarrettP2